
services:
  nats:
    image: bitnami/nats:2.10.18
    ports:
      - '4242:4222'
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: islom0811
      POSTGRES_DB: task_management
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
