
services:
  nats:
    image: bitnami/nats:2.10.18
    ports:
      - '4242:4222'
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: islom0811
      POSTGRES_DB: task_management
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=task_management_minio
      - MINIO_ROOT_PASSWORD=task_management_minio
    volumes:
      - 'minio_data:/bitnami/minio/data'
  redis:
    image: redis:7.2.5-alpine
    ports:
      - '6380:6379'


volumes:
  db-data:
  minio_data:
    driver: local
