
services:
  nats:
    image: bitnami/nats:2.10.18
    ports:
      - '4242:4222'
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: islom_user
      MONGO_INITDB_ROOT_PASSWORD: islom0811
    volumes:
      - mongo-data:/data/db
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=task_management_minio
      - MINIO_ROOT_PASSWORD=task_management_minio
    volumes:
      - 'minio_data:/bitnami/minio/data'
  redis:
    image: redis:7.2.5-alpine
    ports:
      - '6380:6379'

volumes:
  mongo-data:
  minio_data:
    driver: local
